/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Menu;

import java.awt.Window;
import java.sql.Connection;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import mobil.mobil;

/**
 *
 * @author ACER
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        header = new javax.swing.JPanel();
        TombolMobil = new javax.swing.JButton();
        TombolPelanggan = new javax.swing.JButton();
        TombilSupplier = new javax.swing.JButton();
        TombolTransaksi = new javax.swing.JButton();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("jCheckBoxMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TombolMobil.setIcon(new javax.swing.ImageIcon("F:\\download\\download 15 5 2024\\car.png")); // NOI18N
        TombolMobil.setText("Data Mobil");
        TombolMobil.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        TombolMobil.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        TombolMobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TombolMobilActionPerformed(evt);
            }
        });

        TombolPelanggan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/client.png"))); // NOI18N
        TombolPelanggan.setText("Data Pelanggan");
        TombolPelanggan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        TombolPelanggan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        TombolPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TombolPelangganActionPerformed(evt);
            }
        });

        TombilSupplier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/showroom.png"))); // NOI18N
        TombilSupplier.setText("Data Supplier");
        TombilSupplier.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        TombilSupplier.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        TombilSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TombilSupplierActionPerformed(evt);
            }
        });

        TombolTransaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/sell.png"))); // NOI18N
        TombolTransaksi.setText("Data Transaksi");
        TombolTransaksi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        TombolTransaksi.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        TombolTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TombolTransaksiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(TombolMobil, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TombolPelanggan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TombilSupplier)
                .addGap(18, 18, 18)
                .addComponent(TombolTransaksi)
                .addGap(20, 20, 20))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TombolMobil, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TombolPelanggan, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TombilSupplier, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TombolTransaksi, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TombolTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TombolTransaksiActionPerformed
        // TODO add your handling code here:
        tutupSemuaJFrame();
        
        new transaksi.transaksi().setVisible(true);
    }//GEN-LAST:event_TombolTransaksiActionPerformed

    private void TombilSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TombilSupplierActionPerformed
        // TODO add your handling code here:       
        tutupSemuaJFrame();
        
        new supplier.supplier().setVisible(true);
    }//GEN-LAST:event_TombilSupplierActionPerformed

    private void TombolMobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TombolMobilActionPerformed
        // TODO add your handling code here:
        tutupSemuaJFrame();

        new mobil().setVisible(true);
    }//GEN-LAST:event_TombolMobilActionPerformed

    private void TombolPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TombolPelangganActionPerformed
        tutupSemuaJFrame();
        new pelanggan.pelanggan().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_TombolPelangganActionPerformed

    private void tutupSemuaJFrame() {
        Window[] daftarJFrame = Window.getWindows(); // Mendapatkan daftar semua jFrame yang terbuka
        for (Window window : daftarJFrame) {
            if (window instanceof JFrame && !window.getClass().getSimpleName().equals("Menu")) {
                window.dispose(); // Menutup jFrame selain jFrame menu
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton TombilSupplier;
    private javax.swing.JButton TombolMobil;
    private javax.swing.JButton TombolPelanggan;
    private javax.swing.JButton TombolTransaksi;
    private javax.swing.JPanel header;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPopupMenu jPopupMenu1;
    // End of variables declaration//GEN-END:variables
}
