/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package transaksi;

import java.sql.Connection;
import javax.swing.JFrame;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ACER
 */
public class transaksi extends javax.swing.JFrame {

    /**
     * Creates new form transaksi
     */
    public transaksi() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        bukaTransaksi();
        prosesPelangganData();
        prosesMobilData();
    }

    private void prosesPelangganData() {
        dataIdPelanggan.removeAllItems();

        try {
            java.sql.Connection conn = Koneksi.koneksi.ConnectionDB();
            java.sql.Statement stmt = conn.createStatement();
            java.sql.ResultSet rs = stmt.executeQuery("SELECT id_pelanggan, "
                    + "no_ktp_pelanggan, nama_pelanggan FROM pelanggan");
            while (rs.next()) {
                String item = String.valueOf(rs.getInt("id_pelanggan") 
                        + " - " + rs.getString("nama_pelanggan")
                        + " - " + rs.getString("no_ktp_pelanggan")
                );
                dataIdPelanggan.addItem(item);
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error loading supplier data: " + e.getMessage());
        }
    }

    private void setPilihanPelanggan(int idSupplier) {
        for (int i = 0; i < dataIdPelanggan.getItemCount(); i++) {
            String item = dataIdPelanggan.getItemAt(i);
            if (Integer.parseInt(item.split(" - ")[0]) == idSupplier) {
                dataIdPelanggan.setSelectedIndex(i);
                break;
            }
        }
    }

    private void prosesMobilData() {
        dataIdMobil.removeAllItems();

        try {
            java.sql.Connection conn = Koneksi.koneksi.ConnectionDB();
            java.sql.Statement stmt = conn.createStatement();
            java.sql.ResultSet rs = stmt.executeQuery("SELECT id_mobil, "
                    + "merek_mobil, harga_sewa_mobil, nopol_mobil, status_mobil FROM mobil");
            while (rs.next()) {
                String item = String.valueOf(rs.getInt("id_mobil") 
                        + " - " + rs.getString("merek_mobil") 
                        + " - " + rs.getString("harga_sewa_mobil")
                        + " - " + rs.getString("nopol_mobil")
                        + " - " + rs.getString("status_mobil")
                );
                dataIdMobil.addItem(item);
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error loading supplier data: " + e.getMessage());
        }
    }

    private void setPilihanMobil(int idSupplier) {
        for (int i = 0; i < dataIdMobil.getItemCount(); i++) {
            String item = dataIdMobil.getItemAt(i);
            if (Integer.parseInt(item.split(" - ")[0]) == idSupplier) {
                dataIdMobil.setSelectedIndex(i);
                break;
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JPanel();
        logo = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        navbar = new javax.swing.JPanel();
        TombolMobil = new javax.swing.JButton();
        TombolPelanggan = new javax.swing.JButton();
        TombilSupplier = new javax.swing.JButton();
        TombolHome = new javax.swing.JButton();
        TombolTransaksi = new javax.swing.JButton();
        main = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        dataTotalHarga = new javax.swing.JTextField();
        dataIdPelanggan = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabel_Transaksi = new javax.swing.JTable();
        Submit = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        Edit = new javax.swing.JButton();
        dataLamaSewa = new javax.swing.JTextField();
        dataId = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        dataIdMobil = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1366, 786));

        header.setPreferredSize(new java.awt.Dimension(1366, 786));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logo.png"))); // NOI18N

        jLabel11.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel11.setText("Jasa Rental Mobil Terpercaya");

        jLabel12.setFont(new java.awt.Font("Microsoft Himalaya", 1, 36)); // NOI18N
        jLabel12.setText("Ahmad Rental Car");

        javax.swing.GroupLayout logoLayout = new javax.swing.GroupLayout(logo);
        logo.setLayout(logoLayout);
        logoLayout.setHorizontalGroup(
            logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel10)
                .addGap(26, 26, 26)
                .addGroup(logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        logoLayout.setVerticalGroup(
            logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoLayout.createSequentialGroup()
                .addComponent(jLabel10)
                .addGap(0, 5, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addContainerGap())
        );

        TombolMobil.setIcon(new javax.swing.ImageIcon("F:\\download\\download 15 5 2024\\car.png")); // NOI18N
        TombolMobil.setText("Data Mobil");
        TombolMobil.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        TombolMobil.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        TombolMobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TombolMobilActionPerformed(evt);
            }
        });

        TombolPelanggan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/client.png"))); // NOI18N
        TombolPelanggan.setText("Data Pelanggan");
        TombolPelanggan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        TombolPelanggan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        TombolPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TombolPelangganActionPerformed(evt);
            }
        });

        TombilSupplier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/showroom.png"))); // NOI18N
        TombilSupplier.setText("Data Supplier");
        TombilSupplier.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        TombilSupplier.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        TombilSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TombilSupplierActionPerformed(evt);
            }
        });

        TombolHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/home.png"))); // NOI18N
        TombolHome.setText("Home");
        TombolHome.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        TombolHome.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        TombolHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TombolHomeActionPerformed(evt);
            }
        });

        TombolTransaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/sell.png"))); // NOI18N
        TombolTransaksi.setText("Data Transaksi");
        TombolTransaksi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        TombolTransaksi.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        TombolTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TombolTransaksiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout navbarLayout = new javax.swing.GroupLayout(navbar);
        navbar.setLayout(navbarLayout);
        navbarLayout.setHorizontalGroup(
            navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navbarLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(TombolHome, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(TombolMobil, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(TombolPelanggan)
                .addGap(20, 20, 20)
                .addComponent(TombilSupplier)
                .addGap(20, 20, 20)
                .addComponent(TombolTransaksi)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        navbarLayout.setVerticalGroup(
            navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navbarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TombolTransaksi)
                    .addComponent(TombolHome)
                    .addComponent(TombilSupplier)
                    .addComponent(TombolPelanggan)
                    .addComponent(TombolMobil))
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(navbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(navbar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, Short.MAX_VALUE)
                    .addGroup(headerLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32))
        );

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Tabel Data Transaksi");

        jLabel2.setText("Id Mobil");

        jLabel4.setText("Lama Sewa");

        jLabel5.setText("Harga Sewa Mobil");

        dataTotalHarga.setEnabled(false);
        dataTotalHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataTotalHargaActionPerformed(evt);
            }
        });

        dataIdPelanggan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "tersedia", "disewa" }));
        dataIdPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataIdPelangganActionPerformed(evt);
            }
        });

        Tabel_Transaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Id pelanggan", "NIK Pelanggan", "Id Mobil", "Lama Sewa", "Total Harga"
            }
        ));
        Tabel_Transaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tabel_TransaksiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabel_Transaksi);

        Submit.setText("Kirim");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });

        Delete.setText("Hapus");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        Edit.setText("Ubah");
        Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditActionPerformed(evt);
            }
        });

        dataLamaSewa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataLamaSewaActionPerformed(evt);
            }
        });

        dataId.setEnabled(false);

        jLabel7.setText("Id Transaksi");

        jLabel8.setText("Id Pelanggan");

        dataIdMobil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "tersedia", "disewa" }));
        dataIdMobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataIdMobilActionPerformed(evt);
            }
        });

        jLabel6.setText("/Hari");

        javax.swing.GroupLayout mainLayout = new javax.swing.GroupLayout(main);
        main.setLayout(mainLayout);
        mainLayout.setHorizontalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainLayout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dataLamaSewa, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                    .addComponent(dataTotalHarga))
                .addGap(18, 18, 18)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
            .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mainLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainLayout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(743, 743, 743))
                        .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, mainLayout.createSequentialGroup()
                                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(mainLayout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(14, 14, 14)
                                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(dataId, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                                    .addComponent(dataIdPelanggan, javax.swing.GroupLayout.Alignment.LEADING, 0, 313, Short.MAX_VALUE)
                                    .addComponent(dataIdMobil, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 701, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, mainLayout.createSequentialGroup()
                                .addGap(116, 116, 116)
                                .addComponent(Edit)
                                .addGap(28, 28, 28)
                                .addComponent(Delete)))
                        .addGroup(mainLayout.createSequentialGroup()
                            .addGap(14, 14, 14)
                            .addComponent(Submit)
                            .addGap(640, 640, 640)))))
        );
        mainLayout.setVerticalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainLayout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dataLamaSewa)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(dataTotalHarga)
                .addGap(131, 131, 131))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mainLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(dataId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dataIdPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dataIdMobil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(20, 20, 20)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Submit)
                        .addComponent(Delete)
                        .addComponent(Edit))
                    .addGap(90, 90, 90)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(107, Short.MAX_VALUE)
                .addComponent(main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(113, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(292, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Tabel_TransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tabel_TransaksiMouseClicked
        // TODO add your handling code here:
        int row = Tabel_Transaksi.getSelectedRow();
        dataId.setText(Tabel_Transaksi.getModel().getValueAt(row, 0).toString());
        dataIdPelanggan.setSelectedItem(Tabel_Transaksi.getModel().getValueAt(row, 1).toString());
        dataIdMobil.setSelectedItem(Tabel_Transaksi.getModel().getValueAt(row, 2).toString());
        dataLamaSewa.setText(Tabel_Transaksi.getModel().getValueAt(row, 4).toString());
        dataTotalHarga.setText(Tabel_Transaksi.getModel().getValueAt(row, 5).toString());
    }//GEN-LAST:event_Tabel_TransaksiMouseClicked

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "INSERT INTO transaksi ("
                    + "pelanggan_id, "
                    + "mobil_id, "
                    + "lama_sewa, "
                    + "total_harga_sewa) "
                    + "VALUES (?, ?, ?, ?)";

            java.sql.Connection conn = Koneksi.koneksi.ConnectionDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql, java.sql.Statement.RETURN_GENERATED_KEYS);
            
            // Mendapatkan ID Pelanggan dari JComboBox
            String selectedPelanggan = (String) dataIdPelanggan.getSelectedItem();
            int idPelanggan = Integer.parseInt(selectedPelanggan.split(" - ")[0]);
            pst.setInt(1, idPelanggan);

            String selectedMobil = (String) dataIdMobil.getSelectedItem();
            int idMobil = Integer.parseInt(selectedMobil.split(" - ")[0]);
            double hargaMobil = Double.parseDouble(selectedMobil.split(" - ")[2]);
            pst.setInt(2, idMobil);

            int lamaSewa = Integer.parseInt(dataLamaSewa.getText());
            pst.setInt(3, lamaSewa);

            double totalHarga = lamaSewa * hargaMobil;
            pst.setDouble(4, totalHarga);

            // Menampilkan total harga sewa di field dataTotalHarga
//            dataTotalHarga.setText(String.format("%.2f", totalHarga));

            int affectedRows = pst.executeUpdate();

            if (affectedRows > 0) {
                java.sql.ResultSet rs = pst.getGeneratedKeys();
                if (rs.next()) {
                    var idTransaksi = rs.getInt(1);
                    JOptionPane.showMessageDialog(null, "Data Mobil Berhasil Disimpan dengan ID: " + idTransaksi);
                }
            }

            // Bersihkan inputan setelah penyimpanan berhasil
            dataIdPelanggan.setSelectedItem("");
            dataIdMobil.setSelectedItem("");
            dataLamaSewa.setText("");
            dataTotalHarga.setText("");
            dataIdPelanggan.setSelectedItem("");

            Tabel_Transaksi.requestFocusInWindow();
            bukaTransaksi();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_SubmitActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "DELETE FROM transaksi WHERE id_transaksi=?";

            java.sql.Connection conn = Koneksi.koneksi.ConnectionDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);

            pst.setInt(1, Integer.parseInt(dataId.getText())); // ID mobil yang akan dihapus

            int affectedRows = pst.executeUpdate();

            if (affectedRows > 0) {
                JOptionPane.showMessageDialog(null, "Data transaksi Berhasil Dihapus");
            } else {
                JOptionPane.showMessageDialog(null, "Gagal Menghapus Data transaksi");
            }
            
            // Bersihkan inputan setelah penyimpanan berhasil
            dataIdPelanggan.setSelectedItem("");
            dataIdMobil.setSelectedItem("");
            dataLamaSewa.setText("");
            dataTotalHarga.setText("");
            dataIdPelanggan.setSelectedItem("");

            Tabel_Transaksi.requestFocusInWindow();

            // Refresh tabel setelah penghapusan data
            bukaTransaksi();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_DeleteActionPerformed

    private void EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "UPDATE transaksi SET "
                    + "pelanggan_id=?, "
                    + "mobil_id=?, "
                    + "total_harga_sewa=?, "
                    + "total_harga_sewa=? "
                    + "WHERE id_transaksi=?";

            java.sql.Connection conn = Koneksi.koneksi.ConnectionDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);

            // Mendapatkan ID supplier dari JComboBox
            String selectedPelanggan = (String) dataIdPelanggan.getSelectedItem();
            int idPelanggan = Integer.parseInt(selectedPelanggan.split(" - ")[0]);
            pst.setInt(1, idPelanggan);

            String selectedMobil = (String) dataIdMobil.getSelectedItem();
            int idMobil = Integer.parseInt(selectedMobil.split(" - ")[0]);
            pst.setInt(2, idMobil);;

            pst.setInt(3, Integer.parseInt(dataLamaSewa.getText()));
            pst.setDouble(4, Double.parseDouble(dataTotalHarga.getText()));
            pst.setInt(5, Integer.parseInt(dataId.getText())); // ID mobil yang akan diubah

            int affectedRows = pst.executeUpdate();
            // Bersihkan inputan setelah penyimpanan berhasil
            dataIdPelanggan.setSelectedItem("");
            dataIdMobil.setSelectedItem("");
            dataLamaSewa.setText("");
            dataTotalHarga.setText("");
            dataIdPelanggan.setSelectedItem("");

            Tabel_Transaksi.requestFocusInWindow();

            // Refresh tabel setelah perubahan data
            bukaTransaksi();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_EditActionPerformed

    private void dataIdPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataIdPelangganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dataIdPelangganActionPerformed

    private void dataLamaSewaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataLamaSewaActionPerformed
        String selectedMobil = (String) dataIdMobil.getSelectedItem();
        double hargaMobil = Double.parseDouble(selectedMobil.split(" - ")[2]);
        int lamaSewa = Integer.parseInt(dataLamaSewa.getText());
        double totalHarga = lamaSewa * hargaMobil;
        
        dataTotalHarga.setText(String.format("%.2f", totalHarga));
    }//GEN-LAST:event_dataLamaSewaActionPerformed

    private void dataIdMobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataIdMobilActionPerformed
         
    }//GEN-LAST:event_dataIdMobilActionPerformed

    private void TombolMobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TombolMobilActionPerformed
        this.setVisible(false);
        new mobil.mobil().setVisible(true);
    }//GEN-LAST:event_TombolMobilActionPerformed

    private void TombolPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TombolPelangganActionPerformed
        this.setVisible(false);
        new pelanggan.pelanggan().setVisible(true);
    }//GEN-LAST:event_TombolPelangganActionPerformed

    private void TombilSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TombilSupplierActionPerformed
        this.setVisible(false);
        new supplier.supplier().setVisible(true);
    }//GEN-LAST:event_TombilSupplierActionPerformed

    private void TombolHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TombolHomeActionPerformed
        this.setVisible(false);
        new Menu.Menu().setVisible(true);
    }//GEN-LAST:event_TombolHomeActionPerformed

    private void TombolTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TombolTransaksiActionPerformed
        this.setVisible(false);
        new transaksi().setVisible(true);
    }//GEN-LAST:event_TombolTransaksiActionPerformed

    private void dataTotalHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataTotalHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dataTotalHargaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new transaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Delete;
    private javax.swing.JButton Edit;
    private javax.swing.JButton Submit;
    private javax.swing.JTable Tabel_Transaksi;
    private javax.swing.JButton TombilSupplier;
    private javax.swing.JButton TombolHome;
    private javax.swing.JButton TombolMobil;
    private javax.swing.JButton TombolPelanggan;
    private javax.swing.JButton TombolTransaksi;
    private javax.swing.JTextField dataId;
    private javax.swing.JComboBox<String> dataIdMobil;
    private javax.swing.JComboBox<String> dataIdPelanggan;
    private javax.swing.JTextField dataLamaSewa;
    private javax.swing.JTextField dataTotalHarga;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel logo;
    private javax.swing.JPanel main;
    private javax.swing.JPanel navbar;
    // End of variables declaration//GEN-END:variables

    private void bukaTransaksi() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Id");
        model.addColumn("Id Pelanggan");
        model.addColumn("NIK Pelanggan");
        model.addColumn("Id Mobil");
        model.addColumn("Lama Sewa");
        model.addColumn("Total Harga");

        try {
            String sql = "SELECT transaksi.id_transaksi, "
                    + "pelanggan.nama_pelanggan, "
                    + "pelanggan.no_ktp_pelanggan, "
                    + "mobil.merek_mobil, "
                    + "transaksi.lama_sewa, "
                    + "transaksi.total_harga_sewa "
                    + "FROM transaksi "
                    + "JOIN pelanggan ON transaksi.pelanggan_id = pelanggan.id_pelanggan "
                    + "JOIN mobil ON transaksi.mobil_id = mobil.id_mobil";
            java.sql.Connection conn = (Connection) Koneksi.koneksi.ConnectionDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            while (res.next()) {
                model.addRow(new Object[]{
                    res.getString("id_transaksi"),
                    res.getString("nama_pelanggan"),
                    res.getString("no_ktp_pelanggan"),
                    res.getString("merek_mobil"),
                    res.getString("lama_sewa"),
                    res.getString("total_harga_sewa")
                });
            }
            Tabel_Transaksi.setModel(model);
        } catch (Exception e) {
            e.printStackTrace(); // Cetak stack trace untuk debugging
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }
}
